workspace:
  base: /drone
  path: src/github.com/owncloud-docker/alpine

branches:
  - master

clone:
  git:
    image: plugins/git:1
    pull: true

pipeline:
  tools:
    image: owncloud/alpine:latest
    pull: true
    commands:
      - bash update-tools.sh

  docker:
    image: plugins/docker:17.12
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: owncloud/alpine
    tags:
      - latest
      - edge
    dry_run: true
    when:
      event: [ pull_request ]

  docker:
    image: plugins/docker:17.12
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: owncloud/alpine
    tags:
      - latest
      - edge
    when:
      event: [ push ]

  microbadger:
    image: plugins/webhook:1
    pull: true
    secrets: [ webhook_urls ]
    when:
      event: [ push ]

  downstream:
    image: plugins/downstream:1
    pull: true
    secrets: [ drone_token ]
    server: https://drone.owncloud.com
    last_successful: true
    repositories:
      - owncloud-docker/client@master
    when:
      local: false
      event: [ push ]
      status: [ success ]

  slack:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: docker
    when:
      local: false
      event: [ push ]
      status: [ changed, failure ]
