FROM arm64v8/alpine:edge@sha256:fce1d670e6d1dfd6a893ba8e1fd4647d13e8c13f8832901dfc58e07e0662dd3a as build

ENV GOMPLATE_DOWNLOAD=https://github.com/hairyhenderson/gomplate/releases/download/v3.0.0/gomplate_linux-arm64-slim
ENV GOMPLATE_CHECKSUM=af5c65b19ac4cc72a4441e1cb286cfd9114a5fa5a30a8311cbba4d20f23255e0

RUN cd /tmp && \
  wget -O gomplate ${GOMPLATE_DOWNLOAD} && \
  echo "${GOMPLATE_CHECKSUM} *gomplate" | sha256sum -c - && \
  chmod +x gomplate

FROM arm64v8/golang:1.13 as golang

ENV CGO_ENABLED=0
ENV WAIT_FOR_REPO=https://github.com/alioygur/wait-for
ENV WAIT_FOR_COMMIT=a2569b146c861c574e62d416699b78efe66ed883

RUN git clone ${WAIT_FOR_REPO} /go/wait-for && \
  cd /go/wait-for && \
  git checkout ${WAIT_FOR_COMMIT} && \
  go build -v -a -installsuffix cgo -o /tmp/wait-for

FROM arm64v8/alpine:edge@sha256:fce1d670e6d1dfd6a893ba8e1fd4647d13e8c13f8832901dfc58e07e0662dd3a

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>" \
  org.label-schema.name="ownCloud Alpine" \
  org.label-schema.vendor="ownCloud GmbH" \
  org.label-schema.schema-version="1.0"

ENV TERM xterm

COPY ./overlay /
CMD ["bash"]

RUN apk update && \
  apk upgrade && \
  apk add \
    ca-certificates \
    bash \
    vim \
    curl \
    wget \
    bzip2 \
    unzip \
    ncurses \
    tar \
    shadow \
    su-exec \
    git && \
  rm -rf /var/cache/apk/*

COPY --from=build /tmp/gomplate /usr/bin/gomplate
COPY --from=golang /tmp/wait-for /usr/bin/wait-for
